### PR TITLE
Improved accuracy

### PR DESCRIPTION
**Pull request by taoeffect**
Hi, I've improved the accuracy of your filter.

### CODE REVIEW

**Comment by mgeorg** [comment]
Go away troll.

**Comment by taoeffect** [comment]
This extension is one massive troll. 😂

**Comment by taoeffect** [comment]
People who push "fake news" blockers are not liberals, they are basically modern day book burners.

**Comment by bfeldman** [comment]
Then it's a good thing this browser extension — that people can choose to install or not — doesn't actually block anything.

**Comment by taoeffect** [comment]
> doesn't actually block anything.

No, it's only imposing your (@bfeldman's) personal views upon everyone who installs it. This is disgraceful.

**Comment by bfeldman** [comment]
From the Readme:

> This program is not perfect. For one thing, it works off of a static, incomplete list of websites. If there is one feature that should be added, it is the ability [for users] to tweak and customize that list as needed.

**Comment by taoeffect** [comment]
I read your silly readme. Your extension is not just "not perfect", it's a direct assault on everyone's intelligence that takes us back to Nazi book burning times.

**Comment by bfeldman** [comment]
Welp, I tried responding to this in good faith and got called a Nazi. So I'm gonna close this request now.

**Comment by taoeffect** [comment]
> Welp, I tried responding to this in good faith and got called a Nazi. So I'm gonna close this request now.

Maybe try not behaving like a Nazi and you won't get called one?

**Pull request closed without merging**
